<div class="row">
    <div class="col-md-5">
        <div id="newSearchPlaceReceipts"></div>
    </div>
    <div class="col-md-2">
        <div id="newPaginateReceipts"></div>
    </div>

    <div class="col-md-5">
        
        <div id="newSearchLengthReceipts" style="float: right"></div>
    </div> 
</div>

<div id="newInfoReceipts"></div>

<button type="button" class="btn btn-primary" data-toggle="modal" id="editReceipt">
Edit Selected
</button>

<table id="receiptssearch" class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Date</th>
            <th>Amount</th>
            <th>Description</th>
            <th>Image</th>
            <th>Generated by Employee</th>
            <th>Entered By Employee</th>
        </tr>
    </thead>
    <tfoot style="visibility: hidden;">
        <tr>
            <th>ID</th>
            <th>Date</th>
            <th>Amount</th>
            <th>Description</th>
            <th>Image</th>
            <th>Generated by Employee</th>
            <th>Entered By Employee</th>
        </tr>
    </tfoot>
    <tbody>
        @foreach($vendor->receipts as $receipt)
            <tr>
                <td>{{ $receipt->id }}</td>
                <td>{{ $receipt->formatDate() }}</td>
                <td>{{ $receipt->formatedAmount() }}</td>
                <td>{{ $receipt->description  }}</td>
                <td>
                    <div class="hover_img">
                        <a href="#">Show Image<span><img src="{{ $receipt->image }}" alt="image" height="250" /></span></a>
                    </div>
                </td>
                <td>{{ $receipt->getUser()  }}</td>
                <td>{{ $receipt->getEnteredUser()  }}</td>
            </tr>
        @endforeach
    </tbody>
</table>

<script>
$(document).ready(function() {
    
    $('#editReceipt').click(function(e) {
        $row = receiptssearch.row('.selected').data();
        console.log($row);
        var link = document.createElement('a');
        link.href = "/Reciepts/Edit/" + $row[0];
        link.id = "link";
        document.body.appendChild(link);
        link.click(); 
        
    }); 
        // Setup - add a text input to each footer cell0
    $('#receiptssearch tfoot th').each( function () {
        var title = $(this).text();
        $(this).html( '<input class="form-control" type="text" placeholder="Search '+title+'" />' );
    });

    // DataTable
    var receiptssearch = $('#receiptssearch').DataTable({
        "columnDefs": [
            { "targets": [0],"visible": false}
        ],
        "language": {
            "emptyTable": "No Data"
        },
        "order": [[ 0, "desc" ]]
    });

    // Apply the search
    receiptssearch.columns().every( function () {
        var that = this;
 
        $( 'input[type*="search"]', this.footer() ).on( 'keyup change', function () {
            if ( that.search() !== this.value ) {
                that
                    .search( this.value )
                    .draw();
            }
        });
    });
    
        $('#receiptssearch tbody').on( 'click', 'tr', function () {
        $row = $(this);
        if ( $(this).hasClass('selected') ) {
            $(this).removeClass('selected');
        }
        else {
            receiptssearch.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
        }
    } );

    $("#newSearchPlaceReceipts").html($( "#receipts" ).children().find(".dataTables_filter"));
    $("#newSearchLengthReceipts").html($( "#receipts" ).children().find(".dataTables_length"));
    $("#newPaginateReceipts").html($( "#receipts" ).children().find(".dataTables_paginate"));
    $("#newInfoReceipts").html($( "#receipts" ).children().find(".dataTables_info"));
    $("#receiptssearch").css("width" , "100%");
    
} ); 
</script>