<div class="row" style="margin-top: 15px;">
    <div class="col-md-3">
        <div class="input-group ">
            <span class="input-group-addon" for="search"><div style="width: 7em;">Search:</div></span>
            <input id="receipt-search" name="receipt-search" type="text" placeholder="" value="" class="form-control">
        </div>
    </div>
    <div class="col-md-6">
        {!! PageElement::TableControl('receipt') !!}
    </div>
    <div class="col-md-3">
        <button type="button" class="btn OS-Button" data-toggle="modal" id="editReceipt" style="width: 100%;">
            Edit Selected
        </button>
    </div>
</div>



<table id="receiptssearch" class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Date</th>
            <th>Amount</th>
            <th>Description</th>
            <th>Generated By</th>
            <th>Entered By</th>
            <th>Added to Quote</th>
            <th class="col-md-1">Attachment</th>
        </tr>
    </thead>
    <tfoot style="visibility: hidden;">
        <tr>
            <th>ID</th>
            <th>Date</th>
            <th>Amount</th>
            <th>Description</th>
            <th>Generated By</th>
            <th>Entered By</th>
            <th>Added to Quote</th>
            <th class="col-md-1">Attachment</th>
        </tr>
    </tfoot>
    <tbody>
        @foreach($vendor->receipts as $receipt)
            <tr>
                <td>{{ $receipt->id }}</td>
                <td>{{ $receipt->formatDate() }}</td>
                <td>{{ $receipt->formatedAmount() }}</td>
                <td>{{ $receipt->description  }}</td>
                <td>{{ $receipt->getUser()  }}</td>
                <td>{{ $receipt->getEnteredUser()  }}</td>
                <td><a href="/Quote/Edit/{{ $receipt->getQuoteID() }}">{{ $receipt->getQuoteNumber()  }}</a></td>
                <td>
                    @if($receipt->HasAttachment())
                        <button style="width: 100%;" type="button" class="btn OS-Button" data-toggle="modal" data-target="#filestore-display-model" data-fileid="{{ $receipt->filestore->id }}">Show Attachment</button>
                    @endif
                </td>
            </tr>
        @endforeach
    </tbody>
</table>

<script>
$(document).ready(function() {

    $('#editReceipt').click(function(e) {
        $row = receiptssearch.row('.selected').data();
        GoToPage("/Reciepts/Edit/" + $row[0]);
    });

    // DataTable
    var receiptssearch = $('#receiptssearch').DataTable({
        "columnDefs": [
            { "targets": [0],"visible": false}
        ],
        "language": {
            "emptyTable": "No Data"
        },
        "order": [[ 0, "desc" ]]
    });

    $( "#receipt-previous-page" ).click(function() {
        receiptssearch.page( "previous" ).draw('page');
        PageinateUpdate(receiptssearch.page.info(), $('#receipt-next-page'), $('#receipt-previous-page'),$('#receipt-tableInfo'));
    });

    $( "#receipt-next-page" ).click(function() {
        receiptssearch.page( "next" ).draw('page');
        PageinateUpdate(receiptssearch.page.info(), $('#receipt-next-page'), $('#receipt-previous-page'),$('#receipt-tableInfo'));
    });

    $('#receipt-search').on( 'keyup change', function () {
        receiptssearch.search( this.value ).draw();
        PageinateUpdate(receiptssearch.page.info(), $('#receipt-next-page'), $('#receipt-previous-page'),$('#receipt-tableInfo'));
    });

    PageinateUpdate(receiptssearch.page.info(), $('#receipt-next-page'), $('#receipt-previous-page'),$('#receipt-tableInfo'));

    $( "#receipts" ).children().find(".dataTables_filter").css('display', 'none');
    $( "#receipts" ).children().find(".dataTables_length").css('display', 'none');
    $( "#receipts" ).children().find(".dataTables_paginate").css('display', 'none');
    $( "#receipts" ).children().find(".dataTables_info").css('display', 'none');
    $('#receiptssearch').css('width' , "100%");


    $('#receiptssearch tbody').on( 'click', 'tr', function () {
        $row = $(this);
        if ( $(this).hasClass('selected') ) {
            $(this).removeClass('selected');
        }
        else {
            receiptssearch.$('tr.selected').removeClass('selected');
            $(this).addClass('selected');
        }
    } );
    
} ); 
</script>